# Generated by Django 3.0.4 on 2020-05-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField(max_length=255)),
                ('event_time', models.DateTimeField()),
                ('token_time', models.DateTimeField()),
                ('token_end_time', models.DateTimeField()),
                ('event_details', models.TextField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='EventToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.IntegerField()),
                ('timing', models.DateTimeField()),
                ('username', models.TextField(max_length=255)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Event')),
            ],
        ),
    ]
