# Generated by Django 3.0.4 on 2020-05-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200509_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timeslot_in_mins',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
