# Generated by Django 3.0.4 on 2020-05-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200509_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='details',
        ),
        migrations.AlterField(
            model_name='event',
            name='token_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
